set -g mouse on
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:RGB"
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g default-shell "/data3/yky/miniforge3/envs/shell-tools/bin/zsh"
set-environment -g SHELL "/data3/yky/miniforge3/envs/shell-tools/bin/zsh"
